alsa_hw_mapping: 1
beep_reduction: 24
beep_increase: 10
buffer_size: 4096
channels: 1
hook_gpio: 25
playback_reduction: 16
playback_increase: 10
recording_limit: 60
rotary_gpio: 23
rotary_hold_repeat: true
rotary_hold_time: 0.25
sample_rate: 44100
source_file: "audioGuestBook.py"
